!set_default axnum: null

plot_method:
  func: biocomp.plotutils.smooth
  kwargs:
    plot_data: ${D}
    ax: ${FIG.flat_ax if axnum is None else FIG.flat_ax[axnum]}
    xtitle: ${get_pretty_axis_label(0, D)}
    ytitle: ${get_pretty_axis_label(1, D)}
    vtitle: ${D.output_name}
