!set_default axnum: null
!set_default nslices: 30
!set_default threshold: 0.0235
!set_default opacity: 0.25
!set_default zlims: [0, 0.6]

!set_default slices: ${linspace(zlims[0], zlims[1], int(nslices))}

plot_config:
  <<: !include pkg:biocomptools:configs/plot_config/default_plotconf_v2
  <<{+<}:
    # rc_context:
    #   figure.subplot.wspace: 0.1
    #   figure.constrained_layout.wspace: 0.1
    callstack_params:
      smooth_3d_params:
        draw_colorbar: true
        show_inner_spines: false
        show_slice_ticks: false
        show_front_face_ticks: true
        xaxis_labelpad: 10
        yaxis_labelpad: 10
        colorbar_position: [1.5, 0.4]
        cube_edge_props:
          bottom_right:
            zaxis_title:
              offset: [50, 0]
        smooth_2d_params:
          knn_grid_params:
            grid_resolution: 100
            knn_stats_params:
              density_power: 1
              # weight_by_densities: true
              weight_by_densities: false
              # adaptive_sigma: true
              k: 100
              min_points: 5
              radius: 0.10
          heatmap_params:
            opacity: ${float(opacity)}
            show_image: True
            clip_to_lowest_contour: True
            contours:
              - ${float(threshold)}
            contours_linewidth: 0.2

plot_method:
  func: biocomp.plotutils.smooth
  kwargs:
    plot_data: ${D}
    zslices: ${[slices]}
    ax: ${FIG.flat_ax if axnum is None else FIG.flat_ax[axnum]}
    xtitle: ${get_pretty_axis_label(0, D)}
    ytitle: ${get_pretty_axis_label(1, D)}
    ztitle: ${get_pretty_axis_label(2, D)}
    vtitle: ${D.output_name}
