!set_default axnum: null
!set_default nslices: 25
!set_default threshold: 0.225
!set_default opacity: 0.25
!set_default zlims: [0, 0.6]

!set_default slices: ${linspace(zlims[0], zlims[1], int(nslices))}

plot_config:
  <<: !include pkg:biocomptools:configs/plot_config/default_plotconf_v2
  <<{+<}:
    callstack_params:
      knn_stats_params:
        k: 1000
        min_points: 25
        radius: 0.12

      smooth_3d_params:
        draw_colorbar: false
        show_inner_spines: false
        show_slice_ticks: false
        show_front_face_ticks: true
        xaxis_labelpad: 10
        yaxis_labelpad: 10
        cube_edge_props:
          bottom_right:
            zaxis_title:
              offset: [50, 0]

        smooth_2d_params:
          knn_grid_params:
            grid_resolution: 70
          heatmap_params:
            opacity: ${float(opacity)}
            show_image: True
            clip_to_lowest_contour: True
            contours:
              - ${float(threshold)}
            contours_linewidth: 0.2

plot_method:
  func: biocomp.plotutils.smooth
  kwargs:
    plot_data: ${D}
    zslices: ${[slices]}
    ax: ${FIG.flat_ax if axnum is None else FIG.flat_ax[axnum]}
    xtitle: ${get_pretty_axis_label(0, D)}
    ytitle: ${get_pretty_axis_label(1, D)}
    ztitle: ${get_pretty_axis_label(2, D)}
    vtitle: ${D.output_name}
