# -------- main
protein_aliases: { "EBFP": "EBFP2", "L0.G_MNEONGREEN": "MNEONGREEN" }

db:
  postgre:
    name: ${getenv('BIOCOMP_DB_NAME', 'biocomp')}
    user: ${getenv('BIOCOMP_DB_USER', 'biocomp')}
    port: ${getenv('BIOCOMP_DB_PORT', 5432)}
    pass: ${getenv('BIOCOMP_DB_PASS')}
    host: ${getenv('BIOCOMP_DB_HOST')}

  sqlite:
    path: ${getenv('BIOCOMP_SQLITE_DB_PATH', '${&/paths.root}/biocompdb.sqlite')}
    backup:
      dir: ${getenv('BIOCOMP_SQLITE_DB_BACKUP_DIR', '${&/paths.root}/db_backups/')}
      keep_n: ${getenv('BIOCOMP_SQLITE_DB_BACKUP_KEEP_N', 50)}

  gsheet:
    google_app_credentials_path: ${getenv('BIOCOMP_GOOGLE_APP_CREDENTIALS_PATH', '/Users/jeandisset/.google/biocomp/key.json')}
    parts_sheet_key: "1K_2bt90E-Wk-A9PYGXGbKDJy-olojKtksy1jxCQAzME"

paths:
  root: ${getenv('BIOCOMP_ROOT', '~/Dropbox (MIT)/Biocomp_v2')}
  cache:
    base_dir: ${getenv('BIOCOMP_CACHE_DIR', '${&/paths.root}/__cache')}
    networks: ${getenv('BIOCOMP_NETWORK_CACHE_DIR', '${&base_dir}/networks')}
    xp: ${getenv('BIOCOMP_NETWORK_CACHE_DIR', '${&base_dir}/xp')}
    data: ${getenv('BIOCOMP_DATA_CACHE_DIR', '${&base_dir}/data')}

mlflow:
  server: ${getenv('BIOCOMP_MLFLOW_SERVER', 'https://mlf.rachael.jdisset.com')}

calib:
  paths:
    - "./data/calibrated"
  name_priority:
    - "FINAL-*"
    - "final-*"
    - "regular-*"
    - "regular*"

logging:
  default_level: INFO
  use_rich_handler: true
  show_time: true
  show_path: true
  show_level: true
  enable_link_path: true
  rich_tracebacks: true
  omit_repeated_times: true
  markup: false

  rich_format: "[%(name)s] %(message)s"
  file_format: "%(asctime)s %(levelname)s %(name)s: %(message)s" # Standard format for file logs
  worker_format: "[%(processName)s] %(asctime)s %(levelname)s %(name)s: %(message)s" # Format for worker processes
  date_format: "%Y-%m-%d %X"

  format_examples:
    simple: "%(message)s"
    basic: "%(levelname)s: %(message)s"
    standard: "%(asctime)s %(levelname)s %(name)s: %(message)s"
    detailed: "%(asctime)s [%(name)s] %(levelname)s: %(message)s"
    full: "%(asctime)s %(levelname)s [%(name)s:%(lineno)d]: %(message)s"
    process_thread: "[%(process)d/%(threadName)s] %(name)s %(levelname)s: %(message)s"
    custom_time: "[%(asctime)s.%(msecs)03d] %(levelname)s [%(name)s]: %(message)s"
    compact: "%(asctime)s|%(levelname)s|%(name)s|%(message)s"
    dev_debug: "%(asctime)s.%(msecs)03d %(levelname)-8s [%(name)s:%(filename)s:%(lineno)d] %(message)s"

  levels:
    biocomptools.run_training: INFO
    biocomptools.toollib.datasources: DEBUG
    biocomptools.toollib.networkselector: DEBUG
    biocomptools.toollib.networkprediction: DEBUG
    biocomptools.toollib.models: DEBUG
    biocomptools.toollib.plot: DEBUG
    biocomptools.toollib.trainutils: DEBUG
    biocomptools.mlflowlogger: DEBUG
    biocomptools.modelmodel: DEBUG
    biocomptools.plot: DEBUG
    biocomp.train: DEBUG

    biocomp: INFO
    biocomp.compute: INFO
    biocomp.nodes: INFO
    dracon.commandline: INFO
    dracon.instructions: INFO
    matplotlib: WARNING
    matplotlib.font_manager: ERROR
    fontTools: WARNING
    PIL: WARNING
    jax: WARNING
    ray: WARNING
    h5py: WARNING
    parso: WARNING
    numexpr: WARNING
    mlflow: WARNING
    docker: WARNING
    git: WARNING
