defaults:
  - rescaler: EBFP2_compressed

_target_: biocomp.datautils.DataConfig
valid_raw_value_range:
  min: 500.0
  max: 100000000.0
acceptable_out_of_range_fraction_in_raw_data: 0.05
perform_data_checks: true
resampling:
  kde_bw_method: 0.02
  kde_samples: 4000
  density_chunksize: 50000
  density_threshold_quantile: 0.025
  density_threshold_coords: 0.15
rescaler:  ???

