# -------- main
protein_aliases: { "EBFP": "EBFP2", "L0.G_MNEONGREEN": "MNEONGREEN" }

db:
  postgre:
    name: ${getenv('BIOCOMP_DB_NAME', 'biocomp')}
    user: ${getenv('BIOCOMP_DB_USER', 'biocomp')}
    port: ${getenv('BIOCOMP_DB_PORT', 5432)}
    pass: ${getenv('BIOCOMP_DB_PASS')}
    host: ${getenv('BIOCOMP_DB_HOST')}

  sqlite:
    path: ${getenv('BIOCOMP_SQLITE_DB_PATH', '${&/paths.root}/biocompdb.sqlite')}
    backup:
      dir: ${getenv('BIOCOMP_SQLITE_DB_BACKUP_DIR', '${&/paths.root}/db_backups/')}
      keep_n: ${getenv('BIOCOMP_SQLITE_DB_BACKUP_KEEP_N', 50)}

  gsheet:
    google_app_credentials_path: ${getenv('BIOCOMP_GOOGLE_APP_CREDENTIALS_PATH', '/Users/jeandisset/.google/biocomp/key.json')}
    parts_sheet_key: "1K_2bt90E-Wk-A9PYGXGbKDJy-olojKtksy1jxCQAzME"

paths:
  root: ${getenv('BIOCOMP_ROOT', '~/Dropbox (MIT)/Biocomp')}
  cache:
    base_dir: ${getenv('BIOCOMP_CACHE_DIR', '${&/paths.root}/__cache')}
    networks: ${getenv('BIOCOMP_NETWORK_CACHE_DIR', '${&base_dir}/networks')}
    xp: ${getenv('BIOCOMP_NETWORK_CACHE_DIR', '${&base_dir}/xp')}
    data: ${getenv('BIOCOMP_DATA_CACHE_DIR', '${&base_dir}/data')}

calib:
  paths:
    - "./data/calibrated"
  name_priority:
    - "regular-*"
    - "regular*"
