nouns:
  - abecedarian
  - adagio
  - aficionado
  - agog
  - akimbo
  - alfresco
  - aloof
  - ambrosial
  - amok
  - ampersand
  - anemone
  - anthropomorphic
  - aplomb
  - apogee
  - appaloosa
  - apparatus
  - archipelago
  - atingle
  - avuncular
  - azure
  - babushka
  - bailiwick
  - bafflegab
  - balderdash
  - bamboozle
  - bandwagon
  - barnstorming
  - beanpole
  - bedlam
  - berserk
  - bibliopole
  - bigmouth
  - blabbermouth
  - blatherskite
  - blindside
  - blob
  - blockhead
  - blowback
  - blowhard
  - blubbering
  - bluestockings
  - boing
  - bonanza
  - boondocks
  - boondoggle
  - borborygmus
  - bozo
  - braggadocio
  - brainstorm
  - brannigan
  - breakneck
  - brouhaha
  - buckaroo
  - buffoon
  - bugaboo
  - bugbear
  - bumbledom
  - bumfuzzle
  - bumpkin
  - bungalow
  - bunkum
  - bupkis
  - burnsides
  - busybody
  - cacophony
  - cahoots
  - calamity
  - calliope
  - candelabra
  - canoodle
  - cantankerous
  - catamaran
  - catastrophe
  - catawampus
  - caterwaul
  - chatterbox
  - chichi
  - chimerical
  - chimichanga
  - chitchat
  - clandestine
  - claptrap
  - clishmaclaver
  - clodhopper
  - coccyx
  - cockamamie
  - cockatoo
  - codswallop
  - collywobbles
  - colossus
  - comeuppance
  - concoction
  - conniption
  - contraband
  - conundrum
  - corkscrew
  - cornucopia
  - cowabunga
  - coxcomb
  - crackerjack
  - crescendo
  - crestfallen
  - cryptozoology
  - cuckoo
  - curlicue
  - curmudgeon
  - demitasse
  - denouement
  - derecho
  - derring-do
  - desperado
  - digeridoo
  - dilemma
  - dillydally
  - diphthong
  - dirigible
  - discombobulated
  - dodecahedron
  - doldrums
  - donkeyman
  - donnybrook
  - doodad
  - doppelganger
  - dumbwaiter
  - dunderhead
  - earwig
  - eavesdrop
  - ebullient
  - effervescence
  - egads
  - eggcorn
  - egghead
  - elixir
  - ephemeral
  - epiphany
  - ersatz
  - finagle
  - fandango
  - festooned
  - fez
  - fiasco
  - fiddlesticks
  - finicky
  - firebrand
  - fishwife
  - fisticuffs
  - flapdoodle
  - flimflam
  - flippant
  - flophouse
  - flotsam
  - flummery
  - flummoxed
  - flyaway
  - flyspeck
  - folderol
  - foofaraw
  - foolhardy
  - foolscap
  - footloose
  - fopdoodle
  - fortuitous
  - fracas
  - frangipani
  - freewheeling
  - fricassee
  - frippery
  - frogman
  - froufrou
  - fuddy-duddy
  - fussbudget
  - futz
  - gadfly
  - gadzooks
  - gallimaufry
  - gambit
  - gangplank
  - gangway
  - gargoyle
  - gasbag
  - gazebo
  - gazpacho
  - gewgaw
  - genteel
  - ghostwriter
  - gibberish
  - gimcrack
  - gizmo
  - glabella
  - glitch
  - globetrotter
  - gobbledygook
  - gobsmacked
  - googolplex
  - goosebump
  - gooseflesh
  - gorgonzola
  - gossamer
  - grandiloquent
  - greenhorn
  - guffaw
  - gumshoe
  - guru
  - gussied
  - guttersnipe
  - haberdashery
  - haboob
  - hairpin
  - halcyon
  - halfwit
  - hangdog
  - haphazard
  - harebrained
  - harumph
  - headlong
  - heartstrings
  - heebie-jeebie
  - heirloom
  - heyday
  - highfalutin
  - hijinks
  - hillbilly
  - hippocampus
  - hippogriff
  - hobbledehoy
  - hobnobbed
  - hodgepodge
  - hogwash
  - hokum
  - hoodoo
  - hoodwink
  - hooey
  - hooligan
  - hoopla
  - hootenanny
  - hornswoggle
  - horsefeathers
  - hotbed
  - hotfoot
  - hothead
  - hubbub
  - hullabaloo
  - humbug
  - humdinger
  - humdrum
  - hunky-dory
  - hurly-burly
  - hushpuppy
  - huzzah
  - hyperbole
  - idiom
  - idiosyncrasies
  - igloo
  - ignoramus
  - interloper
  - interrobang
  - ironclad
  - izzard
  - jabberwocky
  - jacuzzi
  - jalopy
  - jamboree
  - jargogle
  - jawbreaker
  - jetsam
  - jink
  - jitney
  - jubilee
  - juggernaut
  - jujubes
  - jumbo
  - junket
  - juxtaposition
  - kaleidoscope
  - kaput
  - kerfuffle
  - kerplunk
  - kibosh
  - killjoy
  - kismet
  - knickerbocker
  - knickknack
  - kowtow
  - kumquat
  - kvetch
  - lagoon
  - lambasted
  - lampoon
  - landlubber
  - laughingstock
  - lexicographer
  - limburger
  - lingo
  - loco
  - loggerhead
  - logjam
  - logophile
  - logorrhea
  - lollapalooza
  - lollygag
  - loofah
  - loony
  - loophole
  - lugubrious
  - lummox
  - machinations
  - madcap
  - maelstrom
  - magnificent
  - majordomo
  - malapropism
  - malarkey
  - manifesto
  - mastermind
  - mayhem
  - mealymouthed
  - mellifluous
  - menagerie
  - miasma
  - miffed
  - milquetoast
  - misanthrope
  - mishmash
  - moocher
  - mollycoddle
  - mondegreen
  - moniker
  - monkeyshines
  - monsoon
  - mnemonic
  - moonstruck
  - muckety-muck
  - mudpuppy
  - mudslinger
  - muffuletta
  - mumbo-jumbo
  - murmuration
  - muumuu
  - nabob
  - namby-pamby
  - nimrod
  - nincompoop
  - nitwit
  - nomenclature
  - nonplussed
  - nonilllion
  - nonuplets
  - noodge
  - nudnik
  - numbskull
  - onomatopoeia
  - oomph
  - orotund
  - outfox
  - outlandish
  - oxymoron
  - pachyderm
  - pagoda
  - palindrome
  - palomino
  - panache
  - pandemonium
  - pantaloons
  - papyrus
  - parabola
  - parallelogram
  - parapet
  - paraphernalia
  - peccadillo
  - pedagogue
  - peewee
  - pell-mell
  - persimmon
  - persnickety
  - petrichor
  - pettifogger
  - phalanx
  - phantonym
  - phylactery
  - piffle
  - pizzazz
  - plethora
  - pogo
  - pogonip
  - pollex
  - pollywog
  - poltroon
  - pomposity
  - poppycock
  - portmanteau
  - potpourri
  - pseudonym
  - pugnacious
  - pussyfoot
  - quibble
  - quicksilver
  - quicksticks
  - quiddle
  - quinzee
  - quixotic
  - rabble-rouser
  - raconteur
  - rainmaker
  - ragamuffin
  - ragtag
  - ramshackle
  - ransack
  - rapscallion
  - razzle-dazzle
  - razzmatazz
  - rejigger
  - rendezvous
  - resplendent
  - rickrack
  - ricochet
  - riffraff
  - rigmarole
  - riposte
  - roundabout
  - roustabout
  - rubberneck
  - ruckus
  - ruffian
  - rugrat
  - rumpus
  - sabayon
  - sardoodledom
  - sashay
  - sassafras
  - scatterbrain
  - schadenfreude
  - schlep
  - schmooze
  - schmutz
  - scintillating
  - scrofulous
  - scuttlebutt
  - serendipity
  - sesquipedalian
  - shabang
  - shenanigans
  - skedaddle
  - skirmish
  - skullduggery
  - slapdash
  - slapstick
  - slipshod
  - smithereens
  - smorgasbord
  - snollygoster
  - sobriquet
  - sojourn
  - spellbind
  - squeegee
  - squooshy
  - staccato
  - stupefaction
  - succotash
  - swashbuckler
  - switcheroo
  - swizzlestick
  - talisman
  - taradiddle
  - tchotchke
  - teepee
  - telekinesis
  - thingamabob
  - thingamajig
  - thunderstruck
  - tidbit
  - toadstool
  - toady
  - tomfoolery
  - tommyrot
  - toothsome
  - topsy-turvy
  - trapezoid
  - tub-thumper
  - turducken
  - typhoon
  - ululation
  - umlaut
  - usurp
  - vainglorious
  - vagabond
  - vamoose
  - verboten
  - vertigo
  - verve
  - virtuoso
  - vuvuzela
  - wackadoodle
  - wallflower
  - wanderlust
  - whatsis
  - whirligig
  - whirlybird
  - whizbang
  - whodunit
  - whoop
  - widget
  - wigwam
  - windbag
  - wipeout
  - wiseacre
  - wisecrack
  - wisenheimer
  - woebegone
  - wordplay
  - wordsmith
  - wunderkind
  - wuthering
  - xylophone
  - skedaddle
  - yahoo
  - yokel
  - yo-yo
  - zaftig
  - zeitgeist
  - zephyr
  - zeppelin
  - ziggurat
  - zigzag
  - zonked
  - zoom
  - zydeco
  - zygote

adjectives:
  - bulbous
  - churlish
  - dapper
  - dastardly
  - dotty
  - flippant
  - flummoxed
  - foppish
  - garrulous
  - hoodwinked
  - loquacious
  - lugubrious
  - nincompoop
  - persnickety
  - pugnacious
  - quixotic
  - rickety
  - roustabout
  - scallywag
  - scurrilous
  - slapdash
  - wonky
  - woozy
  - vivacious
  - apoplectic
  - bombastic
  - bumptious
  - supercilious
  - superfluous
  - diaphanous
  - tumultuous
  - impromptu
  - incorrigible
  - incredulous
  - indomitable
  - convivial
  - copacetic
  - coruscating
  - dumbfounded
  - ballistic
  - daft
  - daffy
  - dippy
  - dopey
  - eccentric
  - flaky
  - goofy
  - harebrained
  - hilarious
  - kooky
  - ludicrous
  - loopy
  - madcap
  - nutty
  - outlandish
  - whimsical
  - abominable
  - abstruse
  - acerbic
  - acrimonious
  - adroit
  - affable
  - altruistic
  - amiable
  - amicable
  - amorous
  - amorphous
  - arrogant
  - blunt
  - callous
  - cynical
  - deceitful
  - demanding
  - dishonest
  - egotistical
  - fickle
  - greedy
  - gullible
  - harsh
  - hostile
  - hypocritical
  - impatient
  - inconsiderate
  - indecisive
  - intolerant
  - irresponsible
  - jealous
  - lazy
  - manipulative
  - moody
  - narcissistic
  - neglectful
  - obnoxious
  - overbearing
  - paranoid
  - pessimistic
  - petty
  - prejudiced
  - reckless
  - rude
  - selfish
  - stubborn
  - vindictive
  - assertive
  - authoritative
  - charismatic
  - commanding
  - courageous
  - decisive
  - determined
  - dominant
  - dynamic
  - forceful
  - formidable
  - independent
  - influential
  - innovative
  - intrepid
  - invincible
  - mighty
  - proactive
  - resilient
  - resolute
  - spirited
  - steadfast
  - strong
  - tenacious
  - valiant
  - visionary
  - absurd
  - bizarre
  - blundering
  - bonkers
  - cheeky
  - clownish
  - cockamamie
  - quirky
  - ridiculous
  - silly
  - wacky
  - adaptable
  - agreeable
  - attentive
  - authentic
  - brave
  - calm
  - candid
  - caring
  - cheerful
  - creative
  - curious
  - daring
  - earnest
  - easygoing
  - empathetic
  - energetic
  - faithful
  - fearless
  - generous
  - gracious
  - honest
  - humorous
  - intuitive
  - joyful
  - just
  - kind
  - loyal
  - open
  - optimistic
  - sincere
  - sociable
  - thoughtful
