!define base_range: ${[0.05, 0.7]}

!set_default xlims: ${base_range}
!set_default ylims: ${base_range}
!set_default zlims: ${base_range}
!set_default vlims: ${base_range}
!set_default cmap: bc_blues
!set_default colors_grey: "#000000"

rescaler: !include pkg:biocomptools:configs/data_config/rescaler/EBFP2_compressed_v2

rc_context: !include pkg:biocomptools:configs/plot_config/default_rcparams

callstack_params:
  heatmap_params:
    axtransform: null
    bad_color: "#EEEEEE00"
    cmap: ${cmap}
    contours: 0
    opacities: null
    vlims: ${vlims}

  histogram_params:
    cmap: ${cmap}
    draw_colorbar: true
    noise_smooth: 0
    use_log_density: true
    xlims: ${xlims}
    ylims: ${vlims}
    # vlims: [0, null]
    colorbar_params:
      size: [0.06, 0.85]
      position: [1.05, 0.075]
      tick_props:
        labelsize: 9
        pad: 3
        length: 4

  knn_stats_params:
    k: 1000
    min_points: 20
    radius: 0.1

  knn_grid_params:
    grid_resolution: 250
    is_density_plot: false

  mkfig_params:
    dpi: 300
    size: [20, 4]

  plot_network_params:
    density_quantile_threshold: 0.05
    input_order: null
    kde: null
    use_y_as_x: false
    method: smooth
    protein_aliases: null

  auto_plot_params:
    plot_method_per_input_dim:
      1: smooth
      2: smooth
      3: smooth

  smooth_1d_params:
    xlims: ${xlims}
    vlims: ${vlims}

  smooth_2d_params:
    draw_colorbar: true
    xlims: ${xlims}
    ylims: ${ylims}
    vlims: ${vlims}
    heatmap_params:
      bad_color: "#ffffff"

    colorbar_params:
      size: [0.06, 0.85]
      position: [1.05, 0.075]
      tick_props:
        labelsize: 9
        pad: 3
        length: 4

  smooth_3d_params:
    smooth_2d_params:
      draw_colorbar: false
      heatmap_params:
        bad_color: "#ffffff"
        image_interpolation: "bilinear"
    xlims: ${xlims}
    ylims: ${ylims}
    zlims: ${zlims}
    vlims: ${vlims}
    zslices: [0.05, 0.25, 0.4, 0.55]
    draw_colorbar: null
    colorbar_position: [1.05, 0.4]
    colorbar_size: [0.045, 0.5]
    projection_angle: 45.0
    projection_diag_coef: 0.5
    xaxis_labelpad: 22
    yaxis_labelpad: 25
    zaxis_labelpad: 35
    cube_edge_props:
      bottom_left:
        offset: [0, 0]
        props:
          alpha: 0.5
          color: ${colors_grey}
          linestyle: ":"
          linewidth: 0.5
          zorder: -2147483637
      bottom_right:
        labels:
          major:
            offset: [10, 0]
            props:
              bbox:
                alpha: 1
                edgecolor: none
                facecolor: white
                pad: -0.25
              fontsize: 10
              color: ${colors_grey}
              ha: left
              va: center
          slice:
            offset: [85, 0]
            props:
              fontsize: 7
              color: ${colors_grey}
              ha: left
              va: center
        offset: [0.0, 0]
        props:
          color: ${colors_grey}
          linestyle: "-"
          linewidth: 0.5
          zorder: 2147483637
        ticks:
          major:
            [
              {
                direction: [1, 0, 0],
                length: 6,
                props: { color: "${colors_grey}", linewidth: 0.4 },
              },
            ]
          minor:
            [
              {
                direction: [1, 0, 0],
                length: 2,
                props: { color: "${colors_grey}", linewidth: 0.2 },
              },
            ]
          slice:
            [
              {
                direction: [1, 0, 0],
                length: 80,
                props:
                  {
                    color: "${colors_grey}",
                    alpha: 0.5,
                    dashes: [5, 5],
                    linewidth: 0.2,
                  },
              },
            ]
        zaxis_title:
          offset: [70, 0]
          props:
            fontsize: 10
            rotation: 45
            ha: center
            va: center
            color: ${colors_grey}
      top_left:
        offset: [0, 0]
        props:
          color: ${colors_grey}
          linestyle: "-"
          linewidth: 0.5
          zorder: 2147483637
      top_right:
        offset: [0, 0]
        props:
          color: ${colors_grey}
          linestyle: "-"
          linewidth: 0.5
          zorder: 2147483637
