general:
  base_range: [0.05, 0.7]
  xlims: ${.base_range}
  ylims: ${.base_range}
  zlims: ${.base_range}
  vlims: ${.base_range}
  cmap: bc_blues
  colors:
    grey: '#777777'

rc_context:

  savefig.pad_inches:  0.2
  savefig.dpi: 300

  figure.dpi: 300
  figure.facecolor: white

  axes.labelcolor: ${general.colors.grey}
  axes.labelsize: 8
  axes.labelweight: normal
  axes.spines.bottom: true
  axes.spines.left: true
  axes.spines.right: false
  axes.spines.top: false
  axes.titlecolor: ${general.colors.grey}
  axes.titlesize: 10
  axes.titleweight: normal

  # thin grey spines:
  axes.edgecolor: ${general.colors.grey}
  axes.linewidth: 0.5

  # bigger margin between subplots
  figure.subplot.hspace: 0.75
  figure.subplot.wspace: 0.75


  xtick.color: ${general.colors.grey}
  xtick.labelsize: 8
  xtick.bottom: true
  xtick.labelbottom: true
  xtick.labeltop: false
  xtick.major.size: 5
  xtick.major.width: 0.4
  xtick.minor.size: 2
  xtick.minor.width: 0.2
  xtick.top: false


  ytick.color: ${general.colors.grey}
  ytick.labelsize: 8
  ytick.labelleft: true
  ytick.labelright: false
  ytick.left: true
  ytick.major.size: 5
  ytick.major.width: 0.4
  ytick.minor.size: 2
  ytick.minor.width: 0.2
  ytick.right: false

  # x axis title font should be smaller than the label font


  font.family: sans-serif
  font.monospace: Roboto Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono,
    Courier New, Courier, Fixed, Terminal, monospace
  font.sans-serif: Roboto, DejaVu Sans, Bitstream Vera Sans, Computer Modern Sans Serif,
    Lucida Grande, Verdana, Geneva, Lucid, Arial, Helvetica, Avant Garde, sans-serif
  font.size: 10
  font.stretch: normal
  font.style: normal
  font.variant: normal
  font.weight: normal

  mathtext.bf: sans:bold
  mathtext.bfit: sans:italic:bold
  mathtext.cal: cursive
  mathtext.fallback: stixsans
  mathtext.fontset: custom
  mathtext.it: sans:italic
  mathtext.rm: sans
  mathtext.sf: sans
  mathtext.tt: monospace

  text.latex.preamble: \usepackage{cmbright}
  text.usetex: true


callstack_params:

  heatmap_params:
    axtransform: null
    bad_color: '#EEEEEE00'
    cmap: ${general.cmap}
    contours: 3
    opacities: null
    vlims: ${general.vlims}

  histogram_params:
    cmap: ${general.cmap}
    draw_colorbar: false
    nbins: [256, 256]
    noise_smooth: 0
    use_log_density: true
    vlims: ${general.vlims}
  knn_avg_params:
    avg_method: mean
    k: 500
    min_points: 20
  knn_grid_params:
    grid_resolution: 200
    is_density_plot: false
  mkfig_params:
    dpi: 300
    size: [4, 4]

  plot_network_params:
    density_quantile_threshold: 0.05
    input_order: null
    kde: null
    use_y_as_x: false
    method: smooth
    protein_aliases: null

  auto_plot_params:
    plot_method_per_input_dim:
      1: smooth
      2: smooth
      3: smooth
      
  smooth_2d_params:
    draw_colorbar: true
    xlims: ${general.xlims}
    ylims: ${general.ylims}
    vlims: ${general.vlims}

  smooth_3d_params:
    smooth_2d_params:
      draw_colorbar: false
    xlims: ${general.xlims}
    ylims: ${general.ylims}
    zlims: ${general.zlims}
    vlims: ${general.vlims}
    zslices: [0.05, 0.25, 0.4, 0.55]
    draw_colorbar: null
    colorbar_position: [1.05, 0.4]
    colorbar_size: [0.04, 0.5]
    projection_angle: 45.0
    projection_diag_coef: 0.5
    xaxis_labelpad: 22
    yaxis_labelpad: 25
    zaxis_labelpad: 35
    heatmap_params:
      contours: [0.1, 0.3, 0.5]
    cube_edge_props:
      bottom_left:
        offset: [0, 0]
        props:
          alpha: 0.5
          color: ${general.colors.grey}
          linestyle: ':'
          linewidth: 0.5
          zorder: -2147483637
      bottom_right:
        labels:
          major:
            offset: [10, 0]
            props:
              bbox:
                alpha: 1
                edgecolor: none
                facecolor: white
                pad: -0.25
              fontsize: 8
              color: ${general.colors.grey}
              ha: left
              va: center
          slice:
            offset: [85, 0]
            props:
              fontsize: 7
              color: ${general.colors.grey}
              ha: left
              va: center
        offset: [0.0, 0]
        props:
          color: ${general.colors.grey}
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637
        ticks:
          major: [{direction: [1, 0, 0], length: 8, props: {color: "${general.colors.grey}", linewidth: 0.4}}]
          minor: [{direction: [1, 0, 0], length: 2, props: {color: "${general.colors.grey}", linewidth: 0.2}}]
          slice: [{direction: [1, 0, 0], length: 80, props: {color: "${general.colors.grey}", alpha: 0.5, dashes: [5, 5], linewidth: 0.2}}]
        zaxis_title:
          offset: [60, 0]
          props:
            fontsize: 8
            rotation: 45
            ha: center
            va: center
            color: ${general.colors.grey}
      top_left:
        offset: [0, 0]
        props:
          color: ${general.colors.grey}
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637
      top_right:
        offset: [0, 0]
        props:
          color: ${general.colors.grey}
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637

