!Figure
!set_default D: null # need to pass in the data source
!set_default zmin: 0.05
!set_default zmax: 0.55
!set_default nslices: 3

!noconstruct plot_config: &pconf
  !define plotvars:
    vlims: [null, null]
  <<: !include pkg:biocomptools:configs/plot_config/default_plotconf_v2

figure_spec:
  title: null
  output_dir: # TODO
  output_file: # TODO

!if ${D.dimensions.input <= 2}:
  <<{+<}@figure_spec:
    layout: !SimpleLayout
      cols: 1

  plot_tasks:
    - plot_config: *pconf
      plot_method:
        func: biocomp.plotutils.smooth
        kwargs:
          plot_data: ${D}
          title: # TODO

!if ${D.dimensions.input == 3}:
  <<{+<}@figure_spec:
    layout: !SimpleLayout
      cols: *$nslices

  plot_tasks:
    - plot_config: *pconf
      plot_method:
        func: biocomp.plotutils.smooth
        kwargs:
          plot_data: ${D}
          zslices: ${linspace(zmin, zmax, nslices)}
          title: # TODO
          ax: ${FIG.flat_ax} # passing all axes to the plot method

# data is never > 3D
