!Figure
# we plot a figure with 2 subplots, one for the ground truth and one for the predictions
# EXPECTED VARIABLES:
# - ground_truth_data: list[PlotData]
# - predicted_data: list[PlotData]
!set_default file_prefix: ""
!set_default file_suffix: "_combined_pred.pdf"
!set_default output_dir: "./"

plot_config: !include pkg:biocomptools:configs/plot_config/default_plotconf_v2

figure_spec:
  output_dir: ${output_dir}
  output_file: "${file_prefix + predicted_data.metadata['network_name'] + file_suffix}"
  title: ${ground_truth_data.metadata['file_stem']}
  layout: !SimpleLayout
    cols: 2

plot_tasks:
  - !deferred
    !define D: ${ground_truth_data}
    !define axnum: 0
    <<: !include pkg:biocomptools:configs/plots/tasks/auto
    <<{+<}:
      plot_method:
        kwargs:
          title: "Ground Truth"

  - !deferred
    !define D: ${predicted_data}
    !define _trigger_prediction: ${D.y} # just a trick to trigger the lazy eval'd prediction. (allows access to rmse)

    !define axnum: 1
    <<: !include pkg:biocomptools:configs/plots/tasks/auto

    # <<{+<}:
    #   plot_method:
    #     kwargs:
    #       title: "Predictions (rmse: ${str(round(D.metadata['prediction_stats']['rmse'], 4))})"
