base_plotting_params:
  colormap: bc_blues


plot_callstack_params:
# ┌──────────────────────────┐ 
# │ Base function parameters │ 
# └──────────────────────────┘ 

  heatmap_params:
    axtransform: null
    bad_color: '#EEEEEE00'
    cmap: bc_blues
    contours: 3
    opacities: null
    vlims:
  histogram_params:
    cmap: bc_blues
    draw_colorbar: false
    nbins: [256, 256]
    noise_smooth: 0
    use_log_density: true
    vlims: [0.001, null]
    xlims: [0, 1]
    ylims: [0, 1]
  knn_avg_params:
    avg_method: mean
    k: 500
    min_points: 20
  knn_grid_params:
    grid_resolution: 200
    is_density_plot: false
    knn_avg_params: {}
  mkfig_params:
    dpi: 300
    size: [4, 4]
  network_figure_1d_params:
    mkfig_params: {}
    plot_network_params:
      histogram_params: {}
      smooth_params:
        smooth_2d_params:
          heatmap_params: {}
          knn_grid_params:
            knn_avg_params: {}
        smooth_3d_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
  network_figure_2d_params:
    mkfig_params: {}
    plot_network_params:
      histogram_params: {}
      smooth_params:
        smooth_2d_params:
          heatmap_params: {}
          knn_grid_params:
            knn_avg_params: {}
        smooth_3d_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
  network_figure_3d_params:
    zslices: [0.05, 0.25, 0.4, 0.55]
    mkfig_params: {}
    plot_network_params:
      histogram_params: {}
      smooth_params:
        smooth_2d_params:
          heatmap_params: {}
          knn_grid_params:
            knn_avg_params: {}
        smooth_3d_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
  network_figure_params:
    network_figure_1d_params:
      mkfig_params: {}
      plot_network_params:
        histogram_params: {}
        smooth_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
          smooth_3d_params:
            smooth_2d_params:
              heatmap_params: {}
              knn_grid_params:
                knn_avg_params: {}
    network_figure_2d_params:
      mkfig_params: {}
      plot_network_params:
        histogram_params: {}
        smooth_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
          smooth_3d_params:
            smooth_2d_params:
              heatmap_params: {}
              knn_grid_params:
                knn_avg_params: {}
    network_figure_3d_params:
      mkfig_params: {}
      plot_network_params:
        histogram_params: {}
        smooth_params:
          smooth_2d_params:
            heatmap_params: {}
            knn_grid_params:
              knn_avg_params: {}
          smooth_3d_params:
            smooth_2d_params:
              heatmap_params: {}
              knn_grid_params:
                knn_avg_params: {}
  plot_network_params:
    density_quantile_threshold: 0.05
    histogram_params: {}
    input_order: null
    kde: null
    method: smooth
    protein_aliases: null
    smooth_params:
      smooth_2d_params:
        heatmap_params: {}
        knn_grid_params:
          knn_avg_params: {}
      smooth_3d_params:
        smooth_2d_params:
          heatmap_params: {}
          knn_grid_params:
            knn_avg_params: {}
    use_y_as_x: false
  smooth_2d_params:
    draw_colorbar: true
    heatmap_params: {}
    knn_grid_params:
      knn_avg_params: {}
    title: null
    xlims: [0, 1]
  smooth_3d_params:
    vlims: [0.05, 0.7]
    xlims: [0.01, 0.7]
    ylims: [0.01, 0.7]
    zlims: [0.05, 0.7]
    draw_colorbar: null
    colorbar_position: [1.05, 0.4]
    colorbar_size: [0.04, 0.5]
    projection_angle: 45.0
    projection_diag_coef: 0.5
    cube_edge_props:
      bottom_left:
        offset: [0, 0]
        props:
          alpha: 0.5
          color: '#888888'
          linestyle: ':'
          linewidth: 0.5
          zorder: -2147483637
      bottom_right:
        labels:
          major:
            offset: [10, 0]
            props:
              bbox:
                alpha: 1
                edgecolor: none
                facecolor: white
                pad: -0.25
              fontsize: 8
              ha: left
              va: center
          slice:
            offset: [55, 0]
            props:
              fontsize: 7
              ha: left
              va: center
        offset: [0.0, 0]
        props:
          color: '#888888'
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637
        ticks:
          major: [{direction: [1, 0, 0], length: 8, props: {color: k, linewidth: 0.4}}]
          minor: [{direction: [1, 0, 0], length: 2, props: {color: k, linewidth: 0.2}}]
          slice: [{direction: [1, 0, 0], length: 54, props: {alpha: 0.5, color: k, dashes: [
                  5, 5], linewidth: 0.2}}]
        title:
          offset: [40, 0]
          props:
            fontsize: 8
            ha: center
            rotation: 2578.3100780887044
            va: center
      top_left:
        offset: [0, 0]
        props:
          color: '#888888'
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637
      top_right:
        offset: [0, 0]
        props:
          color: '#888888'
          linestyle: '-'
          linewidth: 0.5
          zorder: 2147483637
    smooth_2d_params:
      draw_colorbar: false
      heatmap_params: 
        contours: [0.1, 0.3, 0.5]
      knn_grid_params:
        knn_avg_params: {}
  smooth_params:
    smooth_2d_params:
      heatmap_params: {}
      knn_grid_params:
        knn_avg_params: {}
    smooth_3d_params:
      smooth_2d_params:
        heatmap_params: {}
        knn_grid_params:
          knn_avg_params: {}


