!Network
!set_default units_names: [x1, x2, b]
!set_default ERNS: [CasE, Csy4, PgU]
!set_default PROMOTER: hEF1a
!set_default TERMINATOR: L0.T_4560
!set_default COLORS: { x1: mKO2, x2: eBFP2, b: mMaroon1, y: mNeonGreen }

!set_default UORFS:
  - null
  - 1w_uORF
  - 1x_uORF
  - 2x_uORF
  - 3x_uORF
  - 4x_uORF
  - 5x_uORF
  - 6x_uORF
  - 8x_uORF

!noconstruct u1: &u1
  part: ${UORFS}
  ref_id: U1

!noconstruct u2: &u2
  part: ${UORFS}
  ref_id: U2

!noconstruct u3: &u3
  part: ${UORFS}
  ref_id: U3

!set_default RECS: ${[ern + "_rec" for ern in ERNS]}

!noconstruct _: &unit
  - !TranscriptionUnit
    slots:
      - !Slot ${PROMOTER}
      - !Slot ${COLORS[tu]}
      - !Slot ${TERMINATOR}
    name: ${tu}_marker
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${&u1}
      - !Slot ${RECS[0]}
      - !Slot ${ERNS[2]}
      - !Slot ${TERMINATOR}
    name: ${tu}_a+
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${ERNS[0]}
      - !Slot ${TERMINATOR}
    name: ${tu}_a-
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${&u2}
      - !Slot ${RECS[1]}
      - !Slot ${ERNS[2]}
      - !Slot ${TERMINATOR}
    name: ${tu}_b+
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${ERNS[1]}
      - !Slot ${TERMINATOR}
    name: ${tu}_b-
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${&u3}
      - !Slot ${RECS[2]}
      - !Slot ${COLORS['y']}
      - !Slot ${TERMINATOR}
    name: ${tu}_c+
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${ERNS[2]}
      - !Slot ${TERMINATOR}
    name: ${tu}_c-
  - !TranscriptionUnit
    slots: !Slot
      - !Slot ${PROMOTER}
      - !Slot ${COLORS['y']}
      - !Slot ${TERMINATOR}
    name: ${tu}_direct_out

cotx:
  !each(n) ${units_names}:
    - name: ${n}
      units:
        - "${&unit:tu=n}"

invert_on_build: true
